export const sample_foods = [
    {
        id: '1',
        name: 'Fried Chicken',
        waitTime: '02-03',
        price: 5,
        favorite: false,
        origins: ['Asia ','India '],
        stars: 4.5,
        imageUrl: 'chicken-1.jpg',
        tags: ['Chicken','Fry','Lunch'],
    },
    {
        id: '2',
        name: 'Fried Egg',
        waitTime: '01-02',
        price: 1,
        favorite: true,
        origins: ['Asia '],
        stars: 5,
        imageUrl: 'egg-1.jpg',
        tags: ['Egg','Fry','Lunch'],
    },
    {
        id: '3',
        name: 'Fried Fish',
        waitTime: '02-03',
        price: 5,
        favorite: false,
        origins: ['Asia '],
        stars: 4.5,
        imageUrl: 'fish-1.jpg',
        tags: ['Fish','Fry','Lunch'],
    },
    {
        id: '4',
        name: 'Fried Rice',
        waitTime: '01-02',
        price: 5,
        favorite: true,
        origins: ['Asia '],
        stars: 4.5,
        imageUrl: 'rice-1.jpg',
        tags: ['Rice','Main','Lunch'],
    },
    {
        id: '5',
        name: 'Salad',
        waitTime: '01-02',
        price: 5,
        favorite: false,
        origins: ['Asia ','US '],
        stars: 4.0,
        imageUrl: 'salad-1.jpg',
        tags: ['Salad','Vegetable'],
    },
    {
        id: '6',
        name: 'Kale With Shiitake',
        waitTime: '01-02',
        price: 3,
        favorite: false,
        origins: ['Asia ','China '],
        stars: 4.2,
        imageUrl: 'vegetable-1.jpg',
        tags: ['Vegetable','Lunch'],
    },
];

export const sample_tags = [
    { name: 'All',count: 6 },
    { name: 'Rice',count: 1 },
    { name: 'Chicken',count: 1 },
    { name: 'Fish',count: 1 },
    { name: 'Vegetable',count: 2 },
    { name: 'Lunch',count: 5 },
    { name: 'Salad',count: 1 },
    { name: 'Fry',count: 3 },
    { name: 'Main',count: 1 },
];

export const sample_users = [
    {
        id: 1,
        name: 'Casper Ng',
        email: 'casper@gmail.com',
        password: 'Zjjz456',
        address: 'Cyber MMU',
        isAdmin: false,
    },
    {
        id: 2,
        name: 'Jing zhi',
        email: 'jingzhi@gmail.com',
        password: 'JzJ12345',
        address: 'Melaka MMU',
        isAdmin: true,
    },
];